### ISSUE TITLE
`Add only` button does not appear for `it.each` or `test.each`

### ISSUE THREAD

**Issue by wdsrocha** [Ub1que/add-only#1]
#### Problem

In order to avoid multiple identical test cases changing only its data, Jest allows the usage of `it.each` or `test.each`, that receives as parameter an array of data and run each data against the test case once. [See the docs for a more detailed explanation](https://jestjs.io/docs/en/api#testeachtablename-fn-timeout).

That being said, during the development of test cases that use `.each`, it would be good to have the `Add only` and `Remove only` button as well, but that does not happen. See the screenshot bellow:

![image](https://user-images.githubusercontent.com/26108090/103133844-a0605b80-468b-11eb-8f49-1b450729e030.png)

The `Add only` button should appear right above line 94 and transform `it.each` into `it.only.each`.

Perhaps I could open a PR to fix this, but I can't run the "development mode" for the VSCode extension, even after running `npm i` and `f5`.

Could you fix this problem or update the contributing guidelines? Thanks!

**Comment by Ub1que** [comment]
Thx. I will fix it.

**Comment by Ub1que** [comment]
It took a while to rework the way it parse code. Now it works properly, even cases like "test.concurrent.only.each". Also added a way of customization.

**Comment by wdsrocha** [comment]
Amazing! Thanks for the quick fix!

**Comment by MaristelaDePaula** [comment]
Hi,
Is there a way to release  a command whit  'remove all only'?

**Comment by wdsrocha** [comment]
Hi @MaristelaDePaula ! I think it would be better to [open a new issue for this feature request](https://github.com/Ub1que/add-only/issues/new), as the discussion here is already closed.
