### ISSUE TITLE
add only button shows up in if statements

### ISSUE THREAD

**Issue by u9g** [Ub1que/add-only#2]
minimal example for the button to show up:
`const _ = /hello/.test('hello')`

![](https://i.imgur.com/elr0usx.png)

A fix for this would be appreciated, thanks :)

**Comment by Ub1que** [comment]
Thanks for reply. The button appears on any call expression where 'test' is a member.  I will fix this asap.

**Comment by u9g** [comment]
Awesome, thanks so much.

**Comment by Ub1que** [comment]
fixed. Now it will not appear if 'test' or 'describe' is a method.
